name: local_config
description: |
  Make changes to your app's default behavior 
  and appearance by changing parameter values 
  â€” just like Firebase Remote Config, but locally.
version: 0.0.4
topics:
  - local
  - config
  - management
  - persistence
  - storage
repository: https://github.com/adrianotelesc/local-config
issue_tracker: https://github.com/adrianotelesc/local-config/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.2
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  get_it: ^7.6.7
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  boxy: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  generate: true

  assets:
    - assets/images/
