name: local_config
description: A Flutter package to manage local configs in your app.
version: 0.0.1
repository: https://github.com/adrianotelesc/local-config

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

flutter:
  generate: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  re_editor: ^0.7.0
  re_highlight: ^0.0.3
  get_it: ^8.2.0
  provider: ^6.1.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
