name: firebase_local_config_sample
description: "A sample demonstrating the usage of the firebase_local_config package"
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_local_config:
    path: ..
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.2
  firebase_remote_config: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
